include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude:
    - '**/*.gr.dart'
    - '**/*.g.dart'
    - '**/*.freezed.dart'

  errors:
    public_member_api_docs: false
    avoid_positional_boolean_parameters: false
    depend_on_referenced_packages: false
    lines_longer_than_80_chars: false
    require_trailing_commas: false
    use_build_context_synchronously: false
    use_full_hex_values_for_flutter_colors: false
